version: '3.8'

services:
  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    depends_on:
      - backend-db
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_HOST=backend-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=1234
      - JWT_KEY=secret

  backend-db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
