version: "3.8"

services:
  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    depends_on:
      - backend-db
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres@backend-db/postgres

  backend-db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
